### ISSUE TITLE
Code duplication between my code and this package

### ISSUE THREAD

**Issue by KristofferC** [JuliaGeometry/HyperRectangles.jl#2]
I noticed that there seem to be some code duplication between stuff I wrote for usage in my kd tree package and this repo, see here:

https://github.com/KristofferC/KDTrees.jl/blob/master/src/hyper_rec.jl

What I have there is basically the same type definition as you have for the HyperRectangle and some functions for calculating the min/max distance between a point and a hyper rectangle and two hyper rectangle. They are currently only implemented for Euclidian distance. I also have a function for splitting a hyper rectangle in a given dimension at a given value.

If this were to be added to this package I could scrap my own code and just use this package instead.

Would a PR with some of these distance functions be of any interest?

**Comment by sjkelly** [comment]
A PR would be great! I have been using the Distances.jl package to overload the `euclidean` method, but your methods seem to be a little bit different.

I was working on an Intervals package so we could correctly, and quickly update the axis bounds. This can come later, but I was hoping to integrate it before the package is registered.

**Comment by KristofferC** [comment]
Thanks for merging.

Now, about the distance calculations. What is needed (at least for `KDTrees.jl`) are functions to calculate min/max distance between two orthotopes (still getting used to the name, I think I prefer "hyper cube" hehe) and an orthotope and a point. Both the total min/max-distance and the distance for one specific dimension.

What I have in the linked file above is just the Euclidian metric but Chebyshev and Manhattan would also be good.

The fastest way I know of doing these are:

Min distance point/orthotope
```julia
 return (max(0, max(rec.mins[dim] - point[dim], point[dim] - rec.maxes[dim])))
```

Max distance point/orthotope
```julia

**Comment by KristofferC** [comment]
Thanks for merging.

Now, about the distance calculations. What is needed (at least for KDTrees.jl) are functions to calculate min/max distance between two orthotopes (still getting used to the name, I think I prefer "hyper cube" hehe) and an orthotope and a point. Both the total min/max-distance and the distance for one specific dimension.

The fastest way I know of doing these are (for a specific dimension):

Min distance point/orthotope
```julia
 (max(0, max(rec.min[dim] - point[dim], point[dim] - rec.max[dim])))
````
Max distance point/orthotope
```julia
abs2(max(rec.max [dim] - point[dim], point[dim] - rec.min[dim]))
```

Min distance orthotope/orthotope
```julia
 abs2(max(0, max(rec1.mins[dim] - rec2.maxes[dim], rec2.mins[dim] - rec1.maxes[dim])))
```

Max distance orhtotope/orthotope
```julia
 abs2(max(rec1.maxes[dim] - rec2.mins[dim],  rec2.maxes[dim] - rec1.mins[dim]))
```

**Comment by KristofferC** [comment]
Finger slip...

**Comment by sjkelly** [comment]
I think intervals is going to need some more work before it is merged. A lot of the API is only 0.4 right now too. It might be best to keep going with the current architecture then switch to Intervals for the next major release.

I am also unopposed to renaming the package 'Hyperrectangles'. 'Hypercubes' doesn't seem quite correct for this package.

I think having these distance functions would be good. They are also useful for my work as well. Maybe we could call the functions `max_euclidean` and `min_euclidean` and leave them unexported for now. I don't think min/max makes much sense in the `Distances.jl` package since it is all vector/vector, but it seems to be a more broad definition than just one that should just be exported from Orthotopes.

Thanks again for all your contributions!

**Comment by KristofferC** [comment]
Yes, I meant hyper rectangles of course :) Orthotopes is a cool name but I think maybe it is a bit too cool for its own good. I had no idea what "orthotope" meant and it was just luck that I found out that this package was about rectangles in many dimensions.

I will draft a PR that adds the distances and then we can discuss the specifics there.

Cheers.

**Comment by KristofferC** [comment]
Closing this with my PR. Sorry for it taking so long time, been kinda busy.
